---
kind: ServiceAccount
apiVersion: v1

metadata:
   name: tiller
   namespace: kube-system

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1

metadata:
   name: tiller-role
   namespace: kube-system

subjects:
- kind: ServiceAccount
  name: tiller
  namespace: kube-system

roleRef:
   kind: ClusterRole
   apiGroup: rbac.authorization.k8s.io
   name: cluster-admin
