apiVersion: v1
kind: Namespace
metadata:
   name: myns
   labels:
      app.kubernetes.io/name: myns
      app.kubernetes.io/version: "v1"
      app.kubernetes.io/component: configuration
      app.kubernetes.io/part-of: mysuite
