FROM node:latest

ENV APP_PORT=3000 APP_DIR=/app

WORKDIR ${APP_DIR}

ADD main.js .
ADD package.json .
ADD package-lock.json .
ADD public public
ADD angular angular
ADD views views
ADD config config

RUN touch .angular
RUN npm install 

HEALTHCHECK --interval=15s --timeout=10s \
	CMD curl -f http://localhost:${APP_PORT}/health || exit 1

EXPOSE ${APP_PORT}

ENTRYPOINT [ "node", "main.js" ]

CMD [ "" ]
