apiVersion: apps/v1
kind: Deployment

metadata:
   name: myapp-deploy
   namespace: workshop02
   labels:
      group: workshop02
      name: myapp-deploy

spec:
   replicas: 2 
   selector:
      matchLabels:
         name: myapp-pod
         group: workshop02
   template:
      metadata:
         name: myapp-pod
         labels:
            name: myapp-pod
            group: workshop02
            version: v2
      spec:
         containers:
         - name: myapp
           image: stackupiss/northwind-app:v2
           imagePullPolicy: IfNotPresent
           env:
           - name: DB_HOST
             value: mydb-svc
           - name: DB_USER
             value: root
           - name: DB_PASSWORD
             valueFrom:
                secretKeyRef:
                   name: myapp-secret
                   key: DB_PASSWORD
           - name: INSTANCE_IP_ADDRESS
             valueFrom:
                fieldRef:
                   fieldPath: status.podIP
           resources:
              requests:
                 cpu: 200m
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxSurge: 1
         maxUnavailable: 1
