apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
   name: myapp-hpa
   namespace: workshop02
   labels:
      name: myapp-hpa
      group: workshop02

spec:
   maxReplicas: 4
   minReplicas: 2

   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: myapp-deploy

   targetCPUUtilizationPercentage: 40
